### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kidonng** [kidonng/ncu-net#1]
Some features will be ported to user script (kidonng/cherry#1).

- [ ] ~~Multi language~~
- [x] Detect current network (91fcee0)
- [x] Dedicated config file
- [x] Detect network connectivity
- [x] Support NCUWLAN
- [x] CLI & Publish to npm
- [x] Pack with [pkg](https://github.com/zeit/pkg)
